/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.Hospital;

import Business.Enterprise.HospitalEnterprise;
import Business.Network.Network;
import Business.Organization.HospitalBackOfficerOrganization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JPanel;

/**
 *
 * @author kathe
 */
public class HospitalBackOfficeWorkAreaJPanel extends javax.swing.JPanel {
    JPanel userProcessContainer;
    //private HospitalBackOfficerOrganization hospitalBackOfficeOrganization;
    private HospitalEnterprise hospitalEnterprise;
    private UserAccount userAccount;
    private Network myNetwork;
    /**
     * Creates new form HospitalBackOfficeWorkArea
     */
    public HospitalBackOfficeWorkAreaJPanel(JPanel userProcessContainer,UserAccount userAccount,HospitalEnterprise hospital,Network myNetwork) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.userAccount=userAccount;
        this.hospitalEnterprise=hospital;
        this.myNetwork=myNetwork;
        
        valueLabel.setText(hospital.getName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        valueLabel = new javax.swing.JLabel();
        backJButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        AssignJButton = new javax.swing.JButton();
        processJButton = new javax.swing.JButton();
        submitWorkEvaluationJButton = new javax.swing.JButton();
        submitVolunteerJButton = new javax.swing.JButton();
        volunteerEvalJButton = new javax.swing.JButton();

        valueLabel.setText("<value>");

        backJButton.setText("<<back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel1.setText("Back Office Work Area");

        AssignJButton.setText("Assign Work Requests");
        AssignJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AssignJButtonActionPerformed(evt);
            }
        });

        processJButton.setText("Process Work Requests");
        processJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                processJButtonActionPerformed(evt);
            }
        });

        submitWorkEvaluationJButton.setText("Submit Work Evaluation");
        submitWorkEvaluationJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitWorkEvaluationJButtonActionPerformed(evt);
            }
        });

        submitVolunteerJButton.setText("Submit Volunteer Request");
        submitVolunteerJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitVolunteerJButtonActionPerformed(evt);
            }
        });

        volunteerEvalJButton.setText("Submit Volunteer Evaluation");
        volunteerEvalJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volunteerEvalJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(backJButton)
                        .addGap(34, 34, 34)
                        .addComponent(valueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(volunteerEvalJButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(submitVolunteerJButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(submitWorkEvaluationJButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(processJButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(AssignJButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(112, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(backJButton)
                    .addComponent(valueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(AssignJButton)
                .addGap(18, 18, 18)
                .addComponent(processJButton)
                .addGap(18, 18, 18)
                .addComponent(submitWorkEvaluationJButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(submitVolunteerJButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(volunteerEvalJButton)
                .addContainerGap(94, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void processJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_processJButtonActionPerformed
        // TODO add your handling code here:
        ProcessWorkRequestJPanel processWorkRequestJPanel=new ProcessWorkRequestJPanel(userProcessContainer,userAccount,myNetwork,hospitalEnterprise);
        userProcessContainer.add("ProcessWorkRequestJPanel",processWorkRequestJPanel);
        CardLayout layout=(CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_processJButtonActionPerformed

    private void AssignJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AssignJButtonActionPerformed
        // TODO add your handling code here:
        AssignWorkRequestJPanel assignWorkRequestJPanel=new AssignWorkRequestJPanel(userProcessContainer,userAccount,hospitalEnterprise);
        userProcessContainer.add("AssignWorkRequestJPanel",assignWorkRequestJPanel);
        CardLayout layout=(CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_AssignJButtonActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        //Component component = componentArray[componentArray.length - 1];
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);   
    }//GEN-LAST:event_backJButtonActionPerformed

    private void submitWorkEvaluationJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitWorkEvaluationJButtonActionPerformed
        // TODO add your handling code here:
        SubmitWorkEvaluationJPanel submitWorkEvaluationJPanel=new SubmitWorkEvaluationJPanel(userProcessContainer,userAccount,hospitalEnterprise);
        userProcessContainer.add("SubmitWorkEvaluationJPanel",submitWorkEvaluationJPanel);
        CardLayout layout=(CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_submitWorkEvaluationJButtonActionPerformed

    private void submitVolunteerJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitVolunteerJButtonActionPerformed
        // TODO add your handling code here:
        SubmitVolunteerJPanel submitVolunteerPanel=new SubmitVolunteerJPanel(userProcessContainer,userAccount,hospitalEnterprise,myNetwork);
        userProcessContainer.add("SubmitVolunteerPanel",submitVolunteerPanel);
        CardLayout layout=(CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_submitVolunteerJButtonActionPerformed

    private void volunteerEvalJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volunteerEvalJButtonActionPerformed
        // TODO add your handling code here:
        SubmitVolunteerEvalJPanel submitVolunteerEvalPanel=new SubmitVolunteerEvalJPanel(userProcessContainer,userAccount,hospitalEnterprise);
        userProcessContainer.add("SubmitVolunteerEvalPanel",submitVolunteerEvalPanel);
        CardLayout layout=(CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_volunteerEvalJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AssignJButton;
    private javax.swing.JButton backJButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton processJButton;
    private javax.swing.JButton submitVolunteerJButton;
    private javax.swing.JButton submitWorkEvaluationJButton;
    private javax.swing.JLabel valueLabel;
    private javax.swing.JButton volunteerEvalJButton;
    // End of variables declaration//GEN-END:variables
}
