/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.Donor;

import Business.Enterprise.CharityEnterprise;
import Business.Enterprise.DonorEnterprise;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.DonorWorkRequest;
import Business.WorkQueue.VolunteerWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author lgfx0
 */
public class ProcessDonorJPanel extends javax.swing.JPanel {
    private JPanel userProcessContainer;
    private UserAccount userAccount;
    private DonorEnterprise donor;
    private Network network;
    /**
     * Creates new form DonorWorkAreaJPanel
     */
    public ProcessDonorJPanel(JPanel userProcessContainer,UserAccount userAccount,DonorEnterprise donor, Network network) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.userAccount=userAccount;
        this.donor=donor;
        this.network= network;
        populateTable();
        populateJComboBox();
       
    }
    
    public void populateJComboBox(){
        donorJComboBox.removeAllItems();
        for (Enterprise charity: network.getEnterpriseDirectory().getEnterpriseList()){
            if(charity.getEnterpriseType().toString().equals("Charity")){
                donorJComboBox.addItem(charity.toString());
            }
        }
    }
    
    public void populateTable(){
        DefaultTableModel model = (DefaultTableModel)donorJTable.getModel();
        model.setRowCount(0);
        
        for(WorkRequest request: userAccount.getWorkQueue().getWorkRequestList()){
            DonorWorkRequest drequest = (DonorWorkRequest)request;
            Object[]row = new Object[5];
            row[0]= drequest.getRequestId();
            row[1]= drequest.getToEnterprise()==null?null:drequest.getToEnterprise().getName();
            row[2]= drequest.getSender()==null?null:drequest.getSender().getPerson().getName();
            row[3]= drequest.getDonor().getQuantity();
            row[4]= drequest.getStatus();
            
            model.addRow(row);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        backJButton = new javax.swing.JButton();
        moneyJTextField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        donorJTable = new javax.swing.JTable();
        submitJButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        donorJComboBox = new javax.swing.JComboBox<>();
        updateJButton = new javax.swing.JButton();
        deleteJButton = new javax.swing.JButton();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel1.setText("Number of Money Donate:");

        backJButton.setText("<<back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });

        donorJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Charity", "Donor Name", "Quantity", "Status"
            }
        ));
        jScrollPane1.setViewportView(donorJTable);

        submitJButton.setText("Submit");
        submitJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitJButtonActionPerformed(evt);
            }
        });

        jLabel2.setText("Select the charity to donate:");

        donorJComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        updateJButton.setText("Update");
        updateJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateJButtonActionPerformed(evt);
            }
        });

        deleteJButton.setText("Delete");
        deleteJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))
                                .addGap(81, 81, 81)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(moneyJTextField)
                                    .addComponent(donorJComboBox, 0, 97, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(submitJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(updateJButton)
                                .addGap(18, 18, 18)
                                .addComponent(deleteJButton))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(backJButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 507, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(276, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(backJButton)
                .addGap(53, 53, 53)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(moneyJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(donorJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(deleteJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(submitJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(updateJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(34, 34, 34))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void submitJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitJButtonActionPerformed
        // TODO add your handling code here:
        String money= String.valueOf(moneyJTextField.getText());
        
        DonorWorkRequest donorWorkRequest = new DonorWorkRequest();
        
        if(money==null||money.isEmpty()){
            JOptionPane.showMessageDialog(null, "Please input amount of money!", "CREATE", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        Integer c;
        try {
            c= Integer.parseInt(money);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Invalid number format! ");
            moneyJTextField.setText("");
            return;
        }
        
        if(c<=0){
            JOptionPane.showMessageDialog(null, "Donated Money must be a positive number!"); 
            moneyJTextField.setText("");
            return;
        }
        
        donorWorkRequest.getDonor().setQuantity(c);
        
        Enterprise toEnterprise=null;
        
        for(Enterprise enterprise:network.getEnterpriseDirectory().getEnterpriseList()){
            if(donorJComboBox.getSelectedItem().toString().equals(enterprise.toString())){
                toEnterprise=enterprise;
                donorWorkRequest.setToEnterprise(toEnterprise);
                toEnterprise.getWorkQueue().getWorkRequestList().add(donorWorkRequest);
                
            }
        }
        
        donorWorkRequest.setSender(userAccount);
        donorWorkRequest.setStatus("Donate");
        donorWorkRequest.setFromEnterprise(donor);
        
        userAccount.getWorkQueue().getWorkRequestList().add(donorWorkRequest);
        moneyJTextField.setText("");
        populateTable();
    }//GEN-LAST:event_submitJButtonActionPerformed

    private void updateJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateJButtonActionPerformed
        // TODO add your handling code here:
        
        int selectedRow = donorJTable.getSelectedRow();
        Integer monid = (Integer) donorJTable.getValueAt(selectedRow, 0); 
        String money = String.valueOf(moneyJTextField.getText());
        
        if(selectedRow<0){
            JOptionPane.showMessageDialog(null, "Please select a Row!!"); 
            return;
        } 
        
        DonorWorkRequest drequest=null;
        for(WorkRequest request:userAccount.getWorkQueue().getWorkRequestList()){
                DonorWorkRequest newrequest=(DonorWorkRequest)request;
                if(monid.equals(newrequest.getRequestId())){
                    drequest=newrequest;
                    break;
                }
         }
        
        if(drequest!=null){
            if(drequest.getStatus().equals("Received")){
                JOptionPane.showMessageDialog(this, "The money has been received!", "INFORMATION", JOptionPane.ERROR_MESSAGE);
                moneyJTextField.setText(""); 
                return;
            }

            if(money==null|| money.isEmpty()){
            JOptionPane.showMessageDialog(this, "The money cannot be empty", "INFORMATION", JOptionPane.ERROR_MESSAGE);
            return;
        }
          if(Integer.parseInt(money)<=0){
            JOptionPane.showMessageDialog(this, "The money must be a positive number!", "INFORMATION", JOptionPane.ERROR_MESSAGE);
            moneyJTextField.setText(""); 
            return; 
            }
            
            drequest.getDonor().setQuantity(Integer.parseInt(money));
            
            JOptionPane.showMessageDialog(null, "Updated Successfully!"); 
            moneyJTextField.setText(""); 
        }
        populateTable();
    }//GEN-LAST:event_updateJButtonActionPerformed

    private void deleteJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteJButtonActionPerformed
        // TODO add your handling code here:
        int selectedRow = donorJTable.getSelectedRow();
        
        if(selectedRow >= 0){
            int selectionButton = JOptionPane.YES_NO_OPTION;
            int selectionResult = JOptionPane.showConfirmDialog(null, "Are you sure to delete?", "Warning", selectionButton);
            if(selectionResult == JOptionPane.YES_OPTION){
            
            Integer dw = (Integer) donorJTable.getValueAt(selectedRow, 0);
            DonorWorkRequest drequest=null;
            for(WorkRequest request:userAccount.getWorkQueue().getWorkRequestList()){
                DonorWorkRequest newrequest=(DonorWorkRequest)request;
                if(dw.equals(newrequest.getRequestId())){
                    drequest=newrequest;
                    break;
                }
            }
            
            if(drequest!=null){
                if(drequest.getStatus().equals("Received")){
                    JOptionPane.showMessageDialog(null, "This money has already been received!");  
                    return;
                }
                drequest.getToEnterprise().getWorkQueue().getWorkRequestList().remove(drequest);
                userAccount.getWorkQueue().getWorkRequestList().remove(drequest);
                moneyJTextField.setText("");
                JOptionPane.showMessageDialog(null, "Delete Successfully!");  
                
            }
            populateTable();
        }   
        }else{
            JOptionPane.showMessageDialog(null, "Please select a Row!!");  
        }
        
        
    }//GEN-LAST:event_deleteJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backJButton;
    private javax.swing.JButton deleteJButton;
    private javax.swing.JComboBox<String> donorJComboBox;
    private javax.swing.JTable donorJTable;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField moneyJTextField;
    private javax.swing.JButton submitJButton;
    private javax.swing.JButton updateJButton;
    // End of variables declaration//GEN-END:variables
}
