/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.Hospital;

import Business.Ecosystem.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Enterprise.HospitalEnterprise;
import Business.Network.Network;
import Business.Organization.DoctorOrganization;
import Business.Organization.HospitalBackOfficerOrganization;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.HospitalWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author kathe
 */
public class SubmitWorkRequestJPanel extends javax.swing.JPanel {
    private JPanel userProcessContainer;
    private UserAccount useraccount;
    private HospitalEnterprise hospital;
    private DoctorOrganization drorganization;
    private Network network;
    //SubmitDemandGoodJPanel submitDemandGoodJPanel;
    /**
     * Creates new form CheckWorkRequest
     */
    public SubmitWorkRequestJPanel(JPanel userProcessContainer, UserAccount useraccount,HospitalEnterprise hospital,Network network) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.useraccount=useraccount;
        this.hospital=hospital;
        this.network=network;
        //this.drorganization=drorganization;
        populateTable();
    }
    
    public void populateTable(){
        DefaultTableModel model = (DefaultTableModel)workRequestJTable.getModel();
        model.setRowCount(0);
        
        for(WorkRequest request:useraccount.getWorkQueue().getWorkRequestList()){
            HospitalWorkRequest hrequest=(HospitalWorkRequest)request;
            Object[] row=new Object[6];
            row[0]=hrequest.getRequestId();
            String pattern = "MM-dd-yyyy";
            SimpleDateFormat simpleDateFormat = new SimpleDateFormat(pattern);
            String date = simpleDateFormat.format(hrequest.getRequestDate());
            row[1]=date;
            row[2]=hrequest.getHandler()==null?null:hrequest.getHandler().getPerson().getName();
            row[3]=hrequest.getStatus();
            row[4] =hrequest ;
            
            model.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        workRequestJTable = new javax.swing.JTable();
        backJButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        dateJTextField = new javax.swing.JTextField();
        createJButton = new javax.swing.JButton();
        addDemandGoodJButton = new javax.swing.JButton();
        DeleteJButton = new javax.swing.JButton();
        submitJButton = new javax.swing.JButton();

        workRequestJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Id", "ExpectedDay", "Handler", "Status", "Result"
            }
        ));
        jScrollPane1.setViewportView(workRequestJTable);

        backJButton.setText("<<back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });

        jLabel3.setText("Expected Date");

        dateJTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateJTextFieldActionPerformed(evt);
            }
        });

        createJButton.setText("Create");
        createJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createJButtonActionPerformed(evt);
            }
        });

        addDemandGoodJButton.setText("Add Demand Good");
        addDemandGoodJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addDemandGoodJButtonActionPerformed(evt);
            }
        });

        DeleteJButton.setText("Delete");
        DeleteJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteJButtonActionPerformed(evt);
            }
        });

        submitJButton.setText("Submit");
        submitJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(backJButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(jLabel3)
                                .addGap(38, 38, 38)
                                .addComponent(dateJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(createJButton)
                                .addGap(32, 32, 32)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(submitJButton)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(DeleteJButton)
                                        .addGap(18, 18, 18)
                                        .addComponent(addDemandGoodJButton)))))))
                .addContainerGap(199, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(backJButton)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(dateJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(createJButton)
                    .addComponent(DeleteJButton)
                    .addComponent(addDemandGoodJButton))
                .addGap(28, 28, 28)
                .addComponent(submitJButton)
                .addContainerGap(93, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void dateJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateJTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dateJTextFieldActionPerformed

    private void createJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createJButtonActionPerformed
        // TODO add your handling code here:
        String expectedDate=dateJTextField.getText();
        
        HospitalWorkRequest hospitalWorkrequest=new HospitalWorkRequest();
        Date expectedTime;
        SimpleDateFormat sdf=new SimpleDateFormat("yyyy-MM-dd");
        
        
        if(expectedDate==null||expectedDate.isEmpty()){
            JOptionPane.showMessageDialog(null, "Please input the Expected Date!", "CREATE", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        try{
            expectedTime=sdf.parse(expectedDate);
        }catch (ParseException ex) {
            JOptionPane.showMessageDialog(null, "Please input the correct expected date:yyyy-mm-dd", "Search", JOptionPane.ERROR_MESSAGE);
            return;
        }
        hospitalWorkrequest.setSender(useraccount);
        hospitalWorkrequest.setStatus("Create");
        hospitalWorkrequest.setRequestDate(expectedTime);
                
//        Organization drorganization=null;
//        Organization hospitalBackOfficerOrganization=null;
//                
//        for(Organization organization:hospital.getOrganizationDirectory().getOrganizationList()){
//            if(organization instanceof DoctorOrganization){
//                drorganization=organization;
//                break;
//            }
//        }
//        
//        for(Organization organization:hospital.getOrganizationDirectory().getOrganizationList()){
//            if(organization instanceof HospitalBackOfficerOrganization){
//                hospitalBackOfficerOrganization=organization;
//                break;
//            }
//        }
        hospitalWorkrequest.setFromEnterprise(hospital);
        hospital.getWorkQueue().getWorkRequestList().add(hospitalWorkrequest);
        useraccount.getWorkQueue().getWorkRequestList().add(hospitalWorkrequest);
        
        populateTable();
        dateJTextField.setText("");
        JOptionPane.showMessageDialog(null, "Create Successfully!");
        
    }//GEN-LAST:event_createJButtonActionPerformed

    private void addDemandGoodJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addDemandGoodJButtonActionPerformed
        // TODO add your handling code here:
        int selectedRow=workRequestJTable.getSelectedRow(),col=0;
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(this, "Please select at least a row.", "INFORMATION", JOptionPane.ERROR_MESSAGE);
            return;
        }
        Integer wrSelectedRow=(Integer)workRequestJTable.getValueAt(selectedRow, 0);
        
        HospitalWorkRequest hrequest=null;
        for(WorkRequest request:useraccount.getWorkQueue().getWorkRequestList()){
            HospitalWorkRequest newrequest=(HospitalWorkRequest)request;
            if(wrSelectedRow.equals(newrequest.getRequestId())){
                hrequest=newrequest;
                break;
            }
        }
        this.userProcessContainer.add("SubmitDemandGoodJPanel",new SubmitDemandGoodJPanel(this.userProcessContainer,useraccount,hospital,hrequest));
        CardLayout cLayout = (CardLayout) this.userProcessContainer.getLayout();
        cLayout.next(userProcessContainer);
    }//GEN-LAST:event_addDemandGoodJButtonActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
//        DoctorWorkArea dwjp = (DoctorWorkArea) component;
//        dwjp.populateTable();
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backJButtonActionPerformed

    private void DeleteJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteJButtonActionPerformed
        // TODO add your handling code here:
        int selectedRow =workRequestJTable.getSelectedRow();
        
        if (selectedRow >= 0) {
            int selectionButton = JOptionPane.YES_NO_OPTION;
            int selectionResult = JOptionPane.showConfirmDialog(null, "Are you sure to delete??", "Warning", selectionButton);

            if (selectionResult == JOptionPane.YES_OPTION) {
                Integer wrSelectedRow=(Integer)workRequestJTable.getValueAt(selectedRow, 0);
                
                for(WorkRequest request:useraccount.getWorkQueue().getWorkRequestList()){
                    HospitalWorkRequest newrequest=(HospitalWorkRequest)request;
                    if(wrSelectedRow.equals(newrequest.getRequestId())){
                        useraccount.getWorkQueue().getWorkRequestList().remove(newrequest);
                        hospital.getWorkQueue().getWorkRequestList().remove(newrequest);
                    
                        Enterprise charity=null;
                        for(Enterprise enterprise:network.getEnterpriseDirectory().getEnterpriseList()){
                            if(enterprise.getEnterpriseType().getValue().equals("Charity")){
                                charity=enterprise;
                            }
                        }

                        if(charity!=null){
                            charity.getWorkQueue().getWorkRequestList().remove(newrequest);

                        }
                        
                        break;
                    }
                }
                populateTable();
                dateJTextField.setText("");
                JOptionPane.showMessageDialog(null, "Create Successfully!");
            }

        } else {
            JOptionPane.showMessageDialog(null, "Please select a Row!!");
        }
    }//GEN-LAST:event_DeleteJButtonActionPerformed

    private void submitJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitJButtonActionPerformed
        // TODO add your handling code here:
        int selectedRow =workRequestJTable.getSelectedRow();
        
        if(selectedRow<0){
            JOptionPane.showMessageDialog(this, "Please select at least a row.", "INFORMATION", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        Integer wrSelectedRow=(Integer)workRequestJTable.getValueAt(selectedRow, 0);
        
        HospitalWorkRequest hrequest=null;
         for(WorkRequest request:useraccount.getWorkQueue().getWorkRequestList()){
            HospitalWorkRequest newrequest=(HospitalWorkRequest)request;
            if(wrSelectedRow.equals(newrequest.getRequestId())){
                hrequest=newrequest;
                break;
            }
        }
         
         if(hrequest!=null){
             System.out.println("hrequest!=null");
             if(hrequest.getDemandGoodDirectory().getDemandGoodMap().size()==0){
                 System.out.println("The demand good is null!");
                    JOptionPane.showMessageDialog(null, "This Request Does't have demand good! You can't submit it!");
                    useraccount.getWorkQueue().getWorkRequestList().remove(hrequest);
                    hospital.getWorkQueue().getWorkRequestList().remove(hrequest);
                    
//                    Enterprise charity=null;
//                    for(Enterprise enterprise:network.getEnterpriseDirectory().getEnterpriseList()){
//                        if(enterprise.getEnterpriseType().getValue().equals("Charity")){
//                            charity=enterprise;
//                        }
//                    }
//        
//                    if(charity!=null){
//                        charity.getWorkQueue().getWorkRequestList().remove(hrequest);
//
//                    }
                    //populateTable();
                    //return;
                }else{
                    hrequest.setStatus("Send");
                    dateJTextField.setText("");
                    JOptionPane.showMessageDialog(null, "Submit Successfully!");
                    
                }
         }
        
       populateTable();
    }//GEN-LAST:event_submitJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DeleteJButton;
    private javax.swing.JButton addDemandGoodJButton;
    private javax.swing.JButton backJButton;
    private javax.swing.JButton createJButton;
    private javax.swing.JTextField dateJTextField;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton submitJButton;
    private javax.swing.JTable workRequestJTable;
    // End of variables declaration//GEN-END:variables
}
